apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 2
  labels:
    app: jetty-docker
  name: jetty-docker
spec:
  replicas: 1
  selector:
    app: jetty-docker
    deploymentconfig: jetty-docker
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jetty-docker
        deploymentconfig: jetty-docker
    spec:
      containers:
      - image: jetty-docker:latest
        imagePullPolicy: Always
        name: jetty-docker
        ports:
        - containerPort: 8778
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
